// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wteymuckhdvfmtyjtykg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZXltdWNraGR2Zm10eWp0eWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMjE3NDYsImV4cCI6MjA1NTg5Nzc0Nn0.JL-19Rao45G3XRrMWK3lNuwlpZND59EBEGkX2zQQeBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);